config/routes.rb
Rails.application.routes.draw do
  resources :favorite_parks
  resources :parks
  resources :users
  get "/image-gallery", to: "parks#image_gallery", as: "image_gallery"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite_park.rb
class FavoritePark < ApplicationRecord

    belongs_to :park 
    belongs_to :user 
    
end

app/models/park.rb
class Park < ApplicationRecord

    has_many :favorite_parks 
    has_many :users, through: :favorite_parks 

    def open_time_string
        three_segments = self.opening_time.to_s.split(" ")[1].split(":")
        three_segments[0] + ":" + three_segments[1]
    end 

    def close_time_string
        three_segments = self.closing_time.to_s.split(" ")[1].split(":")
        three_segments[0] + ":" + three_segments[1]
    end

end

app/models/user.rb
class User < ApplicationRecord

    has_many :favorite_parks 
    has_many :parks, through: :favorite_parks
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/favorite_parks_controller.rb
class FavoriteParksController < ApplicationController
end

app/controllers/parks_controller.rb
class ParksController < ApplicationController

    def index
        @parks = Park.all
        @featured_park = Park.first
    end 

    def show
        @park = Park.find(params[:id])
    end 

    def image_gallery 
        render :image_gallery
    end 


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorite_parks_helper.rb
module FavoriteParksHelper
end

app/helpers/parks_helper.rb
module ParksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NationalParks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
    <script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="ui inverted segment">
      <div class="ui inverted secondary pointing menu">
          <%= link_to "All Parks", parks_path, class: "item" %>
          <%= link_to "Image Gallery", image_gallery_path, class: "item" %>
      </div>
    </div>

    <%= yield %>

    <div class="footer">
      <p>Thanks for visiting the parks page!</p>
    </div>

  </body>
</html>

app/views/parks/image_gallery.html.erb
<h1>Image Gallery</h1>
    <div class="image-gallery">
        <%= image_tag("rocky_mountains.jpg", class: "gallery-img", alt: "rocky mountains") %>
        <%= image_tag("coastal_maine.jpg", class: "gallery-img", alt: "coastal maine") %>
        <%= image_tag("redwood_forest.jpg", class: "gallery-img", alt: "redwood forest") %>
        <%= image_tag("bison.jpg", class: "gallery-img", alt: "bison") %>
        <%= image_tag("grand_canyon.jpg", class: "gallery-img", alt: "grand canyon") %>
        <%= image_tag("yosemite.jpg", class: "gallery-img", alt: "yosemite") %>
        <%= image_tag("rocky_mountains.jpg", class: "gallery-img", alt: "rocky mountains") %>
        <%= image_tag("coastal_maine.jpg", class: "gallery-img", alt: "coastal maine") %>
        <%= image_tag("redwood_forest.jpg", class: "gallery-img", alt: "redwood forest") %>
        <%= image_tag("bison.jpg", class: "gallery-img", alt: "bison") %>
        <%= image_tag("grand_canyon.jpg", class: "gallery-img", alt: "grand canyon") %>
        <%= image_tag("yosemite.jpg", class: "gallery-img", alt: "yosemite") %>
        <%= image_tag("rocky_mountains.jpg", class: "gallery-img", alt: "rocky mountains") %>
        <%= image_tag("coastal_maine.jpg", class: "gallery-img", alt: "coastal maine") %>
        <%= image_tag("redwood_forest.jpg", class: "gallery-img", alt: "redwood forest") %>
        <%= image_tag("bison.jpg", class: "gallery-img", alt: "bison") %>
        <%= image_tag("grand_canyon.jpg", class: "gallery-img", alt: "grand canyon") %>
        <%= image_tag("yosemite.jpg", class: "gallery-img", alt: "yosemite") %>
        <%= image_tag("rocky_mountains.jpg", class: "gallery-img", alt: "rocky mountains") %>
        <%= image_tag("coastal_maine.jpg", class: "gallery-img", alt: "coastal maine") %>
        <%= image_tag("redwood_forest.jpg", class: "gallery-img", alt: "redwood forest") %>
        <%= image_tag("bison.jpg", class: "gallery-img", alt: "bison") %>
        <%= image_tag("grand_canyon.jpg", class: "gallery-img", alt: "grand canyon") %>
        <%= image_tag("yosemite.jpg", class: "gallery-img", alt: "yosemite") %>
    </div>

app/views/parks/index.html.erb
<div class='header'>
      <h1 id="main-page-title"> Welcome To MyParkFinder! </h1>
</div>

<div class='intro'>
      <p>The United States has 60 protected areas known as national parks that are operated by the National Park Service, an agency of the Department of the Interior. National parks must be established by an act of the United States Congress. Criteria for the selection of national parks include natural beauty, unique geological features, unusual ecosystems, and recreational opportunities (though these criteria are not always considered together).</p>
</div>

<h3>Check out all of our National Parks. Click on a park for more information!</h3>

<div class='featured-park'>
      <h2>Featured Park: <%= @featured_park.name %></h2>
      <button class="ui violet button"><%= link_to "Visit Park!", park_path(@featured_park) %></button>
</div>

<div class="parks-div">
    
        <% @parks.each do |park| %>
            <p>
                <%= link_to park.name, park_path(park) %>
            </p>
        <% end %>
   
<div>

app/views/parks/show.html.erb
<h1>Welcome to <%= @park.name %>!</h1>

<div class="wrapper">

    <div class='park-image'>
        <%= image_tag("grand_canyon.jpg", class: "gallery-img", alt: "grand canyon") %>
    </div>

    <div class='park-info'>
        <h3>Park Information</h3>
        <h3>Located in <%= @park.city %>, <%= @park.state %>.</h3>
        <h3>Cost of Admission: $<%= @park.admission_price %></h3>
        <h3>Hours of Operation:</h3>
        <p><%= @park.open_time_string %> - <%= @park.close_time_string %></p>
    </div>

    <div class="article-body">
        <p>
            <%= @park.summary %>
        </p> 
    </div>
</div>